config/routes.rb
Rails.application.routes.draw do
  root 'complaints#index'

  namespace :api do
    resources :complaints
  end

  devise_for :naggers
  resources :categories

  resources :censorships

  resources :complaints do
    member do
      get 'loveit'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
  has_many :complaint_categories
  has_many :complaints, through: :complaint_categories
end

app/models/censorship.rb
class Censorship < ActiveRecord::Base
  validates :word, presence: true
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  URL_RGX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z/
  
  validates :name, presence: true
  validates :content, presence: true
  validates :url, format: { with: URL_RGX }, :allow_blank => true
  has_many :loves
  has_many :complaint_categories
  has_many :categories, through: :complaint_categories
  belongs_to :nagger, counter_cache: true


  scope :top5, -> { order('loves_count desc').limit(5) }


end

app/models/complaint_category.rb
class ComplaintCategory < ActiveRecord::Base
  belongs_to :complaint
  belongs_to :category
end

app/models/love.rb
class Love < ActiveRecord::Base
  belongs_to :nagger
  belongs_to :complaint, counter_cache: true
  validates_uniqueness_of :nagger, scope: :complaint_id
end

app/models/nagger.rb
class Nagger < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :loves
  has_many :complaints

  scope :top5, -> { order('complaints_count desc').limit(5) }

end

app/controllers/api/complaints_controller.rb
class Api::ComplaintsController < ApplicationController
	expose(:complaints)
	expose(:complaint, attributes: :complaint_params)

	def index
		render json: complaints
	end

	def new

	end

	def show
		render json: complaint
	end

	def create
		#self.complaint = Complaint.new
		#complaint.nagger_id = complaint.nagger_id
		if complaint.save
			render nothing: true, status: 201
		else
			render json: complaint.errors.to_json, status: 422
		end
	end

	def complaint_params
    	params.require(:complaint).permit(:name, :content, :nagger_id)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_nagger!, only: [:new, :edit, :update, :destroy, :create]
  
  expose(:categories)
  expose(:category, attributes: :category_params)
  expose(:complaints)


  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if category.destroy
      redirect_to categories_path, notice: 'Category was successfully destroyed.'
    else
      redirect_to categories_path, alert: 'Category wasnt destroyed.'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/censorships_controller.rb
class CensorshipsController < ApplicationController
  expose(:censorships)
  expose(:censorship, attributes: :censorship_params)

  def index
  end

  def new
  end

  def edit
  end

  def create
    if censorship.save
      redirect_to censorships_path, notice: 'The word has been added!'
    else
      render action: 'index'
    end
  end

  def update
    if censorship.update(censorship_params)
      redirect_to censorships_path, notice: 'The word has been updated!'
    end
  end

  def destroy
    if censorship.destroy
      redirect_to censorships_path , notice: 'The word has been deleted!'
    else
      redirect_to censorships_path, alert: 'The word wasnt destroyed'
    end
  end

  private

  def censorship_params
    params.require(:censorship).permit(:word)
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
	before_action :authenticate_nagger!, except: [:index, :show]
  before_action :check_date_create, only: [:create]
  expose_decorated(:complaints) { Complaint.order(:id) }
 	expose_decorated(:complaint, attributes: :complaint_params)
  expose(:love)
  expose(:categories)
  expose(:category)
  expose(:complaint_category)

  def index
  end

  def new
  end

  def show
  end

  def create
    complaint.nagger = current_nagger
    if complaint.save
      redirect_to complaint, notice: 'Thank you for your complaint'
    else
      render action: 'new'
    end
  end

  def loveit
    unless complaint.nagger == current_nagger
      love = complaint.loves.build(nagger: current_nagger)
      if love.save
        redirect_to complaints_path
        flash[:notice] = "You love it!"
      else
        redirect_to complaints_path, alert: "You've already loved it!"
      end
    else
      redirect_to complaints_path, alert:  "You can't love yourself!"

    end
  end

  def edit
  end

  def update
    if current_nagger != complaint.nagger
      redirect_to complaints_path
      flash[:alert] = 'You\'re not allowed to update this complaint'
    else
      if self.complaint.update(complaint_params)
        redirect_to complaint_path
        flash[:notice] = 'The complaint has been updated!'
      end
    end
  end

  def destroy
    if current_nagger != complaint.nagger
      redirect_to complaints_path
      flash[:alert] = 'You\'re not allowed to delete this complaint'
    else
      complaint.destroy
      redirect_to complaints_path
      flash[:notice] = 'The complaint has been deleted!'
    end
  end

  private

  def complaint_params
    params.require(:complaint).permit(:name, :content, :url, category_ids: [])
  end

  def check_date_create
    if Complaint.where('nagger_id = ?', current_nagger.id).where('created_at >= ?', Date.today).count > 3
      redirect_to complaints_path
      flash[:alert] = 'Too many complaints, today!'
    end
  end
end

app/helpers/api/complaints_helper.rb
module Api::ComplaintsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/censorships_helper.rb
module CensorshipsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/love_helper.rb
module LoveHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Listing categories

%table.table
  %tr
    %th Name
    %th
    %th
    %th

  - categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = category.name

%h2
  Category complaints
%table.table.table-striped
  - category.complaints.each do |complaint|
    %tr
      %td= complaint.name
      %td= link_to 'Show', complaint_path(complaint)
  

= link_to 'Edit', edit_category_path(category)
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/censorships/_form.html.haml
= form_for censorship do |f|
  - if censorship.errors.any?
    #error_explanation
      %h2= "#{pluralize(censorship.errors.count, "error")} prohibited this censorship from being saved:"
      %ul
        - censorship.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :word
    = f.text_field :word, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/censorships/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Back', censorship_path, class: 'btn btn-primary'

app/views/censorships/index.html.haml
%h1 Listing complaints

= link_to 'New word', new_censorship_path, class: 'btn btn-info', id: 'new_censorship_btn'
%br
%br

%table.table.table-striped.table-hover
  %tr
    %th ID
    %th Word
    %th
    %th

  - censorships.each do |censorship|
    %tr
      %td= censorship.id
      %td= censorship.word
      %td= link_to 'Edit', edit_censorship_path(censorship)
      %td= link_to 'Destroy', censorship, method: :delete, data: { confirm: 'Are you sure?' }

app/views/censorships/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', censorships_path, class: 'btn btn-primary'

app/views/complaints/_form.html.haml
= simple_form_for complaint do |f|
  - if complaint.errors.any?
    #error_explanation
      %h2= "#{pluralize(complaint.errors.count, "error")} prohibited this complaint from being saved:"
      %ul
        - complaint.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
    = f.label :content
    = f.text_area :content, class: 'form-control'
    = f.label :url
    = f.text_field :url, class: 'form-control'
    = f.association :categories,
      collection: Category.all,
      input_html: { class: 'chosen-select' }

  = f.submit 'Save', class: 'btn btn-default'

app/views/complaints/_top_complaints.html.haml
%h1 Top 5 Complaints

%table.table.table-striped.table-hover
  %tr
    %th ID
    %th Name
    %th Count
    %th Link

  - Complaint.top5.each do |complaint|
    %tr
      %td= complaint.id
      %td= complaint.name
      %td= complaint.loves_count
      %td= link_to "link", complaint

%br

app/views/complaints/_top_naggers.html.haml
%h1 Top 5 Naggers

%table.table.table-striped.table-hover
  %tr
    %th ID
    %th Email
    %th Count

  - Nagger.top5.each do |nagger|
    %tr
      %td= nagger.id
      %td= nagger.email
      %td= nagger.complaints_count

%br

app/views/complaints/edit.html.haml
%h1 Editing complaint

= render 'form'

= link_to 'Show', complaint
\|
= link_to 'Back', complaint_path, class: 'btn btn-primary'

app/views/complaints/index.html.haml
%h1 Listing complaints

= link_to 'New complaint', new_complaint_path, class: 'btn btn-info', id: 'new_complaint_btn'
%br
%br

%table.table.table-striped.table-hover
  %tr
    %th Name
    %th Content
    %th Url
    %th Count
    %th
    %th
    %th
    %th <3

  - complaints.each do |complaint|
    %tr
      %td= complaint.censored(:name)
      %td= complaint.censored(:content)
      %td= complaint.link
      %td= complaint.loves.count
      %td= link_to 'Show', complaint
      %td= link_to 'Edit', edit_complaint_path(complaint)
      %td= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' }
      %td= link_to image_tag('heart.png'), loveit_complaint_path(complaint)

= render 'top_naggers'

= render 'top_complaints'
%br

app/views/complaints/new.html.haml
%h1 New complaint

= render 'form'

= link_to 'Back', complaints_path, class: 'btn btn-primary'

app/views/complaints/show.html.haml
%p#notice= notice

%p

  %b Name
  = complaint.censored(:name)
  %br
  %br

  %b Content
  = complaint.censored(:content)
  %br
  %br

  %b Url
  = complaint.link
  %br
  %br

= link_to 'Edit', edit_complaint_path(complaint)
\|
= link_to 'Back', complaints_path, class: 'btn btn-primary'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %span.navbar-brand
            = link_to '» ', root_path
            Nagit
        %p.navbar-text.navbar-right
          - if nagger_signed_in?
            = link_to 'Categories', categories_path, :class => 'navbar-link'
            |
            = link_to 'Censorship', censorships_path, :class => 'navbar-link'
            |
            = link_to 'Edit your profile', edit_nagger_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Logout", destroy_nagger_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to "Sign up", new_nagger_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Login", new_nagger_session_path, :class => 'navbar-link'}
    .container-fluid
      .row
        .col-lg-12
          - if notice
            %p.alert.alert-success= notice
          - if alert
            %p.alert.alert-danger= alert
          = yield

app/views/spambot/send_spam.html.haml
%h1 Top 5 Complaints

%table
  %tr
    %th ID
    %th Name
    %th Count
    %th Link

  - Complaint.top5.each do |complaint|
    %tr
      %td= complaint.id
      %td= complaint.name
      %td= complaint.loves_count
      %td= link_to "link", complaint.url

%br

app/views/spambot/send_spam.text.haml
Spambot#sent_spam

<%= @greeting %>, find me in app/views/spambot/sent_spam.text.erb